spring.application.name=Shopify

spring.datasource.url=jdbc:mysql://localhost:3307/shopify
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

