spring.application.name=PetStore

spring.datasource.url=jdbc:mysql://localhost:3306/petstore
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true