spring.application.name=Go-Grocery

#connecting with MYSQL
spring.datasource.url=jdbc:mysql://localhost:3307/go_grocery
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#to show sql queries on the console
spring.jpa.show-sql=true

#exceuting DDL queries automatically
spring.jpa.hibernate.ddl-auto=update

razorpay.api.key = rzp_test_TiD1BAW7x4d2v2
razorpay.api.secret = NdhGU1ZPuK4b6ZmwXNcWQkGJ